[package]
name = "bass-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
drop_debug = []
bass_fx = []



[dependencies]
bass-sys = "2.1.0"
once_cell = "1.8"